### ISSUE TITLE
Feature Request: Add option to display the Ranks and Files

### ISSUE THREAD

**Issue by KairuDeibisu** [SilentVoid13/Chesser#19]
I appreciate it if you could add the option to see the rank numbers and file letters on the side of the board.

**Comment by chrisgrieser** [comment]
I made a PR which fixes this. Until it's merged, you can use the following CSS snippet to display rank/files again:
```css
body .cg-wrap coords {
  opacity: 1 !important;
}
```
